name: Update Statstics # The name of the workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 0"
  push:
    branches:
      - main
jobs: 
  main: # The name of the job
    runs-on: ubuntu-latest # The type of runner to use
    steps: 
      - name: Check out repository code # The name of the step
        uses: actions/checkout@v4 # The action to use
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # The version of Node.js to use
      - name: Install dependencies
        run: npm install # The command to run
      - name: Run Script
        run: node index.js
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -u "github-actions-bot <support+actions@github.com>" -b release -d ./dist/ --add
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
